task_manager_site/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tasks.urls", namespace="tasks")),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()

tasks/urls.py
from django.urls import path

from tasks.views import (
    index,
    TaskListView,
    TaskDetailView,
    toggle_completed,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    PositionListView,
    PositionDetailView,
    PositionDeleteView,
    PositionCreateView,
    PositionUpdateView,
    TeamListView,
    TeamDetailView,
    TeamDeleteView,
    TeamCreateView,
    TeamUpdateView,
    ProjectListView,
    ProjectDetailView,
    ProjectDeleteView,
    ProjectCreateView,
    ProjectUpdateView,
    project_toggle_completed,
    task_assign,
    task_take,
    task_remove_from_me,
)

urlpatterns = [
    path("", index, name="index"),
    # Task
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/completed/",
        toggle_completed,
        name="toggle-completed"
    ),
    path("tasks/<int:pk>/assign/", task_assign, name="task-assign"),
    path("tasks/<int:pk>/take/", task_take, name="task-take"),
    path(
        "tasks/<int:pk>/remove-from-me/",
        task_remove_from_me,
        name="task-remove-from-me",
    ),
    # TaskType
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path(
        "task-types/<int:pk>/",
        TaskTypeDetailView.as_view(),
        name="task-type-detail"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    # Worker
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    # Position
    path("positions/", PositionListView.as_view(), name="position-list"),
    path(
        "positions/<int:pk>/",
        PositionDetailView.as_view(),
        name="position-detail"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    # Team
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update"
    ),
    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete"
    ),
    # Project
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete"
    ),
    path(
        "projects/<int:pk>/completed/",
        project_toggle_completed,
        name="project-toggle-completed",
    ),
]

app_name = "tasks"

templates/includes/footer_background.html
{% load static %}

<footer class="footer pt-4">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class=" row">
      <div class="col-md-3 mb-4 ms-auto">
        <div>
          <a href="{% url 'tasks:index' %}">
            <h6 class="text-gradient text-primary font-weight-bolder">Task Manager</h6>
          </a>
        </div>
      </div>

      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <a href="{% url 'tasks:task-list' %}" class="text-reset text-decoration-none">
            <h6 class="text-gradient text-primary text-sm">Tasks</h6>
          </a>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tasks:task-type-list' %}">
                Task types
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <a href="{% url 'tasks:worker-list' %}" class="text-reset text-decoration-none">
            <h6 class="text-gradient text-primary text-sm">Workers</h6>
          </a>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tasks:position-list' %}">
                Positions
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <a href="{% url 'tasks:project-list' %}" class="text-reset text-decoration-none">
            <h6 class="text-gradient text-primary text-sm">Projects</h6>
          </a>
        </div>
      </div>

      <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
        <div>
          <a href="{% url 'tasks:team-list' %}" class="text-reset text-decoration-none">
            <h6 class="text-gradient text-primary text-sm">Teams</h6>
          </a>
        </div>
      </div>

      <div class="col-12">
        <div class="text-center">
          <p class="mb-4 text-sm">
            Coded by Ivan Khomych.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer_signin.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
  <div class="container">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-12 col-md-6 my-auto">
        <div class="copyright text-center text-sm text-white text-lg-start">
          Coded by Ivan Khomych.
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
{% load static %}
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
        class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
            href="/" rel="tooltip"
            title="Designed and Coded by Creative Tim" data-placement="bottom">
            Task Manager
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                  href="javascript:;" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Tasks
                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                  aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'tasks:task-list' %}" class="dropdown-item border-radius-md">
                      <span class="">List of tasks</span>
                    </a>
                    <a href="{% url 'tasks:task-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Crate a new task</span>
                    </a>
                    <a href="{% url 'tasks:task-type-list' %}" class="dropdown-item border-radius-md">
                      <span class="">Task types</span>
                    </a>
                    <a href="{% url 'tasks:task-type-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Create a new task type</span>
                    </a>
                  </div>

                  <div class="d-lg-none">
                    <a href="{% url 'tasks:task-list' %}" class="dropdown-item border-radius-md">
                      <span class="">List of tasks</span>
                    </a>
                    <a href="{% url 'tasks:task-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Crate a new task</span>
                    </a>
                    <a href="{% url 'tasks:task-type-list' %}" class="dropdown-item border-radius-md">
                      <span class="">Task types</span>
                    </a>
                    <a href="{% url 'tasks:task-type-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Create a new task type</span>
                    </a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                  href="javascript:;" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Workers
                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                  aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'tasks:worker-list' %}" class="dropdown-item border-radius-md">
                      <span class="">List of workers</span>
                    </a>
                    <a href="{% url 'tasks:worker-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Crate a new worker</span>
                    </a>
                    <a href="{% url 'tasks:position-list' %}" class="dropdown-item border-radius-md">
                      <span class="">Positions</span>
                    </a>
                    <a href="{% url 'tasks:position-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Create a new position</span>
                    </a>
                  </div>

                  <div class="d-lg-none">
                    <a href="{% url 'tasks:worker-list' %}" class="dropdown-item border-radius-md">
                      <span class="">List of workers</span>
                    </a>
                    <a href="{% url 'tasks:worker-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Crate a new worker</span>
                    </a>
                    <a href="{% url 'tasks:position-list' %}" class="dropdown-item border-radius-md">
                      <span class="">Positions</span>
                    </a>
                    <a href="{% url 'tasks:position-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Create a new position</span>
                    </a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                  href="javascript:;" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Projects
                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                  aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'tasks:project-list' %}" class="dropdown-item border-radius-md">
                      <span class="">List of projects</span>
                    </a>
                    <a href="{% url 'tasks:project-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Crate a new project</span>
                    </a>
                  </div>

                  <div class="d-lg-none">
                    <a href="{% url 'tasks:project-list' %}" class="dropdown-item border-radius-md">
                      <span class="">List of projects</span>
                    </a>
                    <a href="{% url 'tasks:project-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Crate a new project</span>
                    </a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                  href="javascript:;" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Teams
                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                  aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'tasks:team-list' %}" class="dropdown-item border-radius-md">
                      <span class="">List of teams</span>
                    </a>
                    <a href="{% url 'tasks:team-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Crate a new team</span>
                    </a>
                  </div>

                  <div class="d-lg-none">
                    <a href="{% url 'tasks:team-list' %}" class="dropdown-item border-radius-md">
                      <span class="">List of teams</span>
                    </a>
                    <a href="{% url 'tasks:team-create' %}" class="dropdown-item border-radius-md">
                      <span class="">Crate a new team</span>
                    </a>
                  </div>
                </div>
              </li>

              {% if request.user.is_authenticated %}
              <li class="nav-item ms-lg-auto">
                <form method="post" action="{% url 'logout' %}" class="d-inline m-0">
                  {% csrf_token %}
                  <button class="nav-link nav-link-icon me-2 bg-transparent border-0" type="submit">
                    <i class="fa fa-sign-out me-1"></i>
                    <span class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="Logout">Logout</span>
                  </button>
                </form>
              </li>
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{{ user.get_absolute_url }}"
                  class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">{{ user.username }}</a>
              </li>
              {% else %}
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2"
                  href="{% url 'login' %}">
                  <i class="fa fa-sign-in me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="Login">Login</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% load static %}
{% if is_paginated %}
  <section class="py-0">
    <div class="container">
      <div class="row justify-space-between py-0">
        <div class="col-lg-4 mx-auto">
          <ul class="pagination pagination-primary justify-content-center m-2">

            {# First #}
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
              <a class="page-link"
                 href="{% if page_obj.has_previous %}?{% query_transform request page=1 %}{% endif %}"
                 aria-label="Previous">
                <i class="icon-angle-double-left"></i>
              </a>
            </li>

            {# Prev #}
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
              <a class="page-link"
                 href="{% if page_obj.has_previous %}?{% query_transform request page=page_obj.previous_page_number %}{% endif %}"
                 aria-label="Previous">
                <i class="icon-angle-left"></i>
              </a>
            </li>

            <li class="page-item active">
              <a class="page-link text-light text-bold" href="#">{{ page_obj.number }}</a>
            </li>

            {# Next #}
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
              <a class="page-link"
                 href="{% if page_obj.has_next %}?{% query_transform request page=page_obj.next_page_number %}{% endif %}"
                 aria-label="Next">
                <i class="icon-angle-right"></i>
              </a>
            </li>

            {# Last #}
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
              <a class="page-link"
                 href="{% if page_obj.has_next %}?{% query_transform request page=paginator.num_pages %}{% endif %}"
                 aria-label="Next">
                <i class="icon-angle-double-right"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endif %}

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>